name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        zig:
          - latest
          - master
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Zig ${{ matrix.zig }}
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig }}
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Tests
        run: zig build test --summary all
